[package]
name = "crucible-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }
phf = { workspace = true }